CC = gcc
CFLAGS = -Wall -g
LEX = flex
YACC = bison
YFLAGS = -d -v

TARGET = semantics
OBJS = lex.yy.o parser.tab.o tree.o semantics.o codegen.o

$(TARGET): $(OBJS)
	$(CC) $(CFLAGS) -o $(TARGET) $(OBJS)

# Compiles the tree logic
tree.o: tree.c tree.h
	$(CC) $(CFLAGS) -c tree.c

# Compiles the semantics logic
semantics.o: semantics.c semantics.h tree.h
	$(CC) $(CFLAGS) -c semantics.c

# Compiles the parser generated by Bison
parser.tab.o: parser.tab.c parser.tab.h tree.h
	$(CC) $(CFLAGS) -c parser.tab.c

# Compiles the lexer generated by Flex
lex.yy.o: lex.yy.c parser.tab.h
	$(CC) $(CFLAGS) -c lex.yy.c

codegen.o: codegen.c codegen.h
	$(CC) $(CFLAGS) -c codegen.c

# Generates parser.tab.c and parser.tab.h
parser.tab.c parser.tab.h: parser.y tree.h
	$(YACC) $(YFLAGS) parser.y 

# Generates lex.yy.c
lex.yy.c: lexer.l parser.tab.h
	$(LEX) lexer.l

clean:
	rm -f $(TARGET) *.o lex.yy.c parser.tab.c parser.tab.h parser.output

test: $(TARGET)
	./run_tests.sh
